- name: Upload docker to rpi
  synchronize:
    src: ../docker/
    dest: ~/CodePlayerBox/scratch-link-node/
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
      - "--exclude=code"
      - "--exclude=script"
      - "--exclude=node_modules"

- name: Upload code to rpi
  synchronize:
    src: ../code/
    dest: ~/CodePlayerBox/scratch-link-node/code
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
      - "--exclude=node_modules"

- name: Upload script to rpi
  synchronize:
    src: ../script/
    dest: ~/CodePlayerBox/scratch-link-node/script
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"

- name: Install all packages
  yarn:
    path: ~/CodePlayerBox/scratch-link-node/code
    production: True
